// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SetBirthDateToNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetBirthDateToNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004141025500_SetBirthDateToNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
